import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'



export default function Home(props) {
    const router = useRouter()
    console.log('posts.props',props)
    const {data} = props
  return (
    <div >
      <Head>
        <title>Posts - {router.query.id}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <h1>POSTS</h1>
    <p>Post id: {router.query.id}</p>
    <p>Title: {data.title}</p>
    <p>
        
        <Image src={data.url} alt="" />
    </p>
    </div>
  )
}


// This gets called on every request
export async function getServerSideProps({ query }) {
    
    // Fetch data from external API
    const res = await fetch(`https://jsonplaceholder.typicode.com/photos/${query.id}`)
    const data = await res.json()
  
    // Pass data to the page via props
    return { props: { data } }
  }